# Generated by Django 5.2.17 on 2026-09-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publie')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='resume')),
                ('brief', models.JSONField(blank=True, default=dict, help_text='Enonce structure en blocs : {"version": 1, "blocks": [...]}.', verbose_name='brief')),
                ('success_criteria', models.JSONField(blank=True, default=list, help_text='Liste de criteres verifiables, presentes en checklist.', verbose_name='criteres de reussite')),
                ('difficulty', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance'), ('expert', 'Expert')], db_index=True, default='intermediate', max_length=20, verbose_name='difficulte')),
                ('estimated_hours', models.PositiveSmallIntegerField(default=2, verbose_name='duree estimee (h)')),
                ('xp_reward', models.PositiveIntegerField(default=200, verbose_name='XP a la completion')),
                ('submission_kind', models.CharField(choices=[('checklist', 'Checklist auto-declaree'), ('graph', 'Graphe colle (V2)')], default='checklist', max_length=20, verbose_name='mode de validation')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='learning.learningpath', verbose_name='parcours')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='unlocks_projects', to='learning.skill', verbose_name='skills prerequis')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('status', models.CharField(choices=[('not_started', 'Non commence'), ('in_progress', 'En cours'), ('completed', 'Termine')], db_index=True, default='not_started', max_length=20, verbose_name='statut')),
                ('checklist_state', models.JSONField(blank=True, default=dict, help_text="Criteres coches par l'utilisateur, indexes par position.", verbose_name='etat de la checklist')),
                ('submission', models.JSONField(blank=True, default=dict, help_text='Vide au MVP ; accueillera le graphe colle en V2.', verbose_name='soumission')),
                ('notes', models.TextField(blank=True, verbose_name='notes personnelles')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='commence le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='termine le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='projects.project', verbose_name='projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_progress', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'progression de projet',
                'verbose_name_plural': 'progressions de projets',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='projectprogress_unique_user_project')],
            },
        ),
    ]
