# Generated by Django 5.2.17 on 2026-09-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Etudiant'), ('instructor', 'Formateur'), ('admin', 'Administrateur')], db_index=True, default='student', max_length=20, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('display_name', models.CharField(blank=True, max_length=60, verbose_name='nom affiche')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='biographie')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='XP total (cache)')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='niveau (cache)')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='serie en cours')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='meilleure serie')),
                ('last_activity_on', models.DateField(blank=True, null=True, verbose_name='derniere activite')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='onboarding termine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
                'indexes': [models.Index(fields=['-total_xp'], name='profile_total_xp_desc_idx')],
            },
        ),
    ]
