# Generated by Django 5.2.17 on 2026-09-21 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('status', models.CharField(choices=[('not_started', 'Non commence'), ('in_progress', 'En cours'), ('completed', 'Termine')], db_index=True, default='not_started', max_length=20, verbose_name='statut')),
                ('completion_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement (%, cache)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='commence le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='termine le')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='learning.learningpath', verbose_name='parcours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'progression de parcours',
                'verbose_name_plural': 'progressions de parcours',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'learning_path'), name='courseprogress_unique_user_path')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('status', models.CharField(choices=[('not_started', 'Non commence'), ('in_progress', 'En cours'), ('completed', 'Termine')], db_index=True, default='not_started', max_length=20, verbose_name='statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='commencee le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminee le')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='derniere consultation')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='learning.lesson', verbose_name='lecon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'progression de lecon',
                'verbose_name_plural': 'progressions de lecons',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='lessonprogress_user_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='lessonprogress_unique_user_lesson')],
            },
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('mastery_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score de maitrise')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='tentatives')),
                ('successes_count', models.PositiveIntegerField(default=0, verbose_name='reussites')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True, verbose_name='derniere pratique')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='learning.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'maitrise de skill',
                'verbose_name_plural': 'maitrises de skills',
                'ordering': ['-mastery_score', 'skill'],
                'indexes': [models.Index(fields=['user', '-mastery_score'], name='skillmastery_user_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='skillmastery_unique_user_skill')],
            },
        ),
    ]
