# Generated by Django 5.2.17 on 2026-09-21 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publie')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('type', models.CharField(choices=[('A', 'A - Question'), ('B', 'B - QCM'), ('C', "C - Remettre dans l'ordre"), ('D', 'D - Node matching'), ('E', 'E - Construction logique (graphe libre)'), ('F', 'F - Debugging (corriger un graphe)'), ('G', 'G - Challenge (objectif a construire)'), ('H', 'H - Completer le graphe'), ('I', "I - Realiser dans Unreal et coller l'export")], db_index=True, max_length=1, verbose_name='type')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('content', models.JSONField(default=dict, help_text="Enonce et donnees de l'exercice. Forme imposee par le type.", verbose_name='contenu')),
                ('solution', models.JSONField(default=dict, help_text='Reponse attendue. Pour les types de production (E/F/G/H/I) : des PROPRIETES a verifier, jamais un graphe exact.', verbose_name='solution')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Indices progressifs, du plus leger au plus explicite.', verbose_name='indices')),
                ('is_practice', models.BooleanField(db_index=True, default=False, editable=False, help_text='Derive du type. Seuls les exercices de production font progresser la maitrise et deverrouillent les prerequis.', verbose_name='exercice de production')),
                ('difficulty', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance'), ('expert', 'Expert')], db_index=True, default='beginner', max_length=20, verbose_name='difficulte')),
                ('xp_reward', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour utiliser la valeur par defaut du type (settings.EXERCISE_XP_DEFAULTS).', null=True, verbose_name='XP a la reussite')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de temps (s)')),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='essais maximum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('lesson', models.ForeignKey(blank=True, help_text='Vide pour un exercice autonome (challenge, entrainement).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.lesson', verbose_name='lecon')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='unlocks_exercises', to='learning.skill', verbose_name='skills prerequis')),
                ('skills', models.ManyToManyField(blank=True, related_name='practiced_by_exercises', to='learning.skill', verbose_name='skills pratiques')),
            ],
            options={
                'verbose_name': 'exercice',
                'verbose_name_plural': 'exercices',
                'ordering': ['lesson', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='numero de tentative')),
                ('submission', models.JSONField(default=dict, help_text="Pour les types de production : un graphe normalise. Pour le type I, le texte colle depuis Unreal est normalise avant d'etre stocke.", verbose_name='soumission')),
                ('raw_submission', models.TextField(blank=True, help_text="Texte d'origine colle par l'utilisateur (type I), pour audit.", verbose_name='soumission brute')),
                ('is_correct', models.BooleanField(default=False, verbose_name='reussie')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0 a 100. Un exercice peut etre partiellement juste.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score')),
                ('feedback', models.JSONField(blank=True, default=dict, help_text='ValidationResult serialise : messages, indices declenches.', verbose_name='retour')),
                ('hints_used', models.PositiveSmallIntegerField(default=0, verbose_name='indices consultes')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duree (s)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise', verbose_name='exercice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'tentative',
                'verbose_name_plural': 'tentatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['type', 'is_published'], name='exercise_type_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_practice', 'is_published'], name='exercise_practice_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_practice', True), ('type__in', ['E', 'F', 'G', 'H', 'I'])), models.Q(('is_practice', False), models.Q(('type__in', ['E', 'F', 'G', 'H', 'I']), _negated=True)), _connector='OR'), name='exercise_is_practice_matches_taxonomy'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'exercise', '-created_at'], name='attempt_user_ex_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['exercise', 'is_correct'], name='attempt_exercise_ok_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciseattempt',
            constraint=models.UniqueConstraint(fields=('user', 'exercise', 'attempt_number'), name='attempt_unique_number_per_user_exercise'),
        ),
    ]
