# Generated by Django 5.2.17 on 2026-09-21 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publie')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='sous-titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('difficulty', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance'), ('expert', 'Expert')], db_index=True, default='beginner', max_length=20, verbose_name='difficulte')),
                ('estimated_hours', models.PositiveSmallIntegerField(default=0, verbose_name='duree estimee (h)')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='image de couverture')),
            ],
            options={
                'verbose_name': 'parcours',
                'verbose_name_plural': 'parcours',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publie')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.learningpath', verbose_name='parcours')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['learning_path', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('fundamentals', 'Fondamentaux'), ('variables', 'Variables et types'), ('flow_control', 'Controle de flux'), ('functions', 'Fonctions et macros'), ('oop', 'Classes, heritage, interfaces'), ('actors', 'Acteurs et composants'), ('input', 'Entrees joueur'), ('ui', 'Interface (UMG)'), ('gameplay', 'Systemes de gameplay'), ('ai', 'Intelligence artificielle'), ('physics', 'Physique et collisions'), ('debugging', 'Debogage'), ('optimization', 'Optimisation')], db_index=True, default='fundamentals', max_length=30, verbose_name='categorie')),
                ('difficulty', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance'), ('expert', 'Expert')], db_index=True, default='beginner', max_length=20, verbose_name='difficulte')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text="Skills a maitriser avant d'aborder celui-ci.", related_name='unlocks', to='learning.skill', verbose_name='prerequis')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['category', 'difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publie')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='resume')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structure : {"version": 1, "blocks": [...]}.', verbose_name='contenu')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duree estimee (min)')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='XP a la completion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module', verbose_name='module')),
                ('required_skills', models.ManyToManyField(blank=True, help_text='Prerequis exprimes en skills, jamais en lecons.', related_name='unlocks_lessons', to='learning.skill', verbose_name='skills prerequis')),
                ('skills_taught', models.ManyToManyField(blank=True, related_name='taught_by_lessons', to='learning.skill', verbose_name='skills enseignes')),
            ],
            options={
                'verbose_name': 'lecon',
                'verbose_name_plural': 'lecons',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='unlocks_paths', to='learning.skill', verbose_name='skills prerequis'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('learning_path', 'slug'), name='module_unique_slug_per_path'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='lesson_unique_slug_per_module'),
        ),
    ]
