# Generated by Django 5.2.17 on 2026-09-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('code', models.SlugField(help_text='Identifiant stable, non traduit.', max_length=80, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icone cote frontend.", max_length=60, verbose_name='icone')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name="XP a l'obtention")),
                ('rule', models.JSONField(default=dict, help_text='Exemple : {"type": "exercises_solved", "threshold": 25}.', verbose_name='regle')),
                ('is_secret', models.BooleanField(default=False, help_text="Masque tant qu'il n'est pas obtenu.", verbose_name='secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'succes',
                'verbose_name_plural': 'succes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='obtenu le')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='gamification.achievement', verbose_name='succes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'succes obtenu',
                'verbose_name_plural': 'succes obtenus',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='userachievement_unique_user_achievement')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positif pour un gain, negatif pour une correction.', verbose_name='montant')),
                ('source', models.CharField(choices=[('lesson_completed', 'Lecon terminee'), ('exercise_solved', 'Exercice reussi'), ('challenge_solved', 'Challenge reussi'), ('project_completed', 'Projet termine'), ('achievement_unlocked', 'Succes debloque'), ('streak_bonus', 'Bonus de serie'), ('manual_adjustment', 'Ajustement manuel')], db_index=True, max_length=30, verbose_name='origine')),
                ('reference_key', models.CharField(blank=True, help_text="Identifie le fait generateur, par exemple 'exercise:42'.", max_length=120, verbose_name='cle de reference')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadonnees')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'transaction XP',
                'verbose_name_plural': 'transactions XP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='xptx_user_date_idx'), models.Index(fields=['-created_at'], name='xptx_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_key', ''), _negated=True), fields=('user', 'source', 'reference_key'), name='xptransaction_idempotent_reference')],
            },
        ),
    ]
